import bass1 from "../img/bass1.png"
import bass2 from "../img/bass2.png"
import bass3 from "../img/bass3.png"
import bass4 from "../img/bass4.png"
import bass0 from "../img/bass0.png"

export const products = [
    {   
        id: 1,
        imgUrl: bass1,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "carcas",
        border: "Металлический",
        size: 2.7,
        height: 60,
    },
    {   
        id: 1,
        imgUrl: bass1,
        oldCost: 1800000,
        newCost: 1520000,
        level: 7,
        category: "carcas",
        border: "Металлический",
        size: 3.5,
        height: 76,
    },
    {   
        id: 1,
        imgUrl: bass1,
        oldCost: 1800000,
        newCost: 1520000,
        level: 7,
        category: "carcas",
        border: "Металлический",
        size: 3.5,
        height: 76,
    },
    {   
        id: 1,
        imgUrl: bass2,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "carcas",
        border: "Прямоугольная",
        size: "3.05 x 2.20",
        height: 84,
    },
    {   
        id: 1,
        imgUrl: bass2,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "carcas",
        border: "Прямоугольная",
        size: "3.05 x 2.20",
        height: 84,
    },
    {   
        id: 1,
        imgUrl: bass3,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "carcas",
        border: "Рамка призмы",
        size: 3.05,
        height: 76,
    },
    {   
        id: 1,
        imgUrl: bass4,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "carcas",
        border: "Прямоугольная",
        size: "2 x 4",
        height: 100,
    },
    {   
        id: 1,
        imgUrl: bass3,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "carcas",
        border: "Рамка призмы",
        size: 3.05,
        height: 76,
    },
    {   
        id: 1,
        imgUrl: bass0,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "bamm",
        border: "Металлический",
        size: 3.66,
        height: 76,
    },
    {   
        id: 1,
        imgUrl: bass0,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "bamm",
        border: "Металлический",
        size: 3.66,
        height: 76,
    },
    {   
        id: 1,
        imgUrl: bass0,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "bamm",
        border: "Металлический",
        size: 3.66,
        height: 76,
    },
    {   
        id: 1,
        imgUrl: bass0,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "bamm",
        border: "Металлический",
        size: 3.66,
        height: 76,
    },
    {   
        id: 1,
        imgUrl: bass0,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "bamm",
        border: "Металлический",
        size: 3.66,
        height: 76,
    },
    {   
        id: 1,
        imgUrl: bass0,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "bamm",
        border: "Металлический",
        size: 3.66,
        height: 76,
    },
    {   
        id: 1,
        imgUrl: bass0,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "bamm",
        border: "Металлический",
        size: 3.66,
        height: 76,
    },
    {   
        id: 1,
        imgUrl: bass0,
        oldCost: 1800000,
        newCost: 1520000,
        level: 10,
        category: "bamm",
        border: "Металлический",
        size: 3.66,
        height: 76,
    },
]